### ISSUE TITLE
Task_29-Implement plugin dependency tracking

### ISSUE THREAD

**Issue by PouyaF1** [DAT265group2/libSMCE#1]
The DEPENDS field of Ardrivo plugins is currently ignored. Sort plugins in reverse dependency

- [x] Research regarding Cmake

- [x] Scan the plugin dependencies and perform topological sorting

- [x] Sort plugins in reverse dependency

- [x] Validating/test

- [x] Scan for cycles

- [x] Validating/test

**Comment by PouyaF1** [comment]
Approved by Ryan. Branch is left for eventual merging with main repo.
